name: MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local
  LD_LIBRARY_PATH: $(pwd)

jobs:
  build:

    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup python
      uses: actions/setup-python@v2
      
    - name: cache dependencies
      uses: actions/cache@v2
      id: cache
      with:
        path: ${{github.workspace}}/${{env.INSTALL_LOCATION}}
        key: ${{runner.os}}-dependencies
          
    - name: Download Conan package manager.
      if: ${{steps.cache.output.cache-hit != 'true'}}
      run: |
        python -m pip install --upgrade pip
        pip install conan
        pip install conan_package_tools

#    - name: install GoogleTest
#      if: ${{steps.cache.output.cache-hit != 'true'}}
#      run: |
#        cd ..
#        git clone https://github.com/google/googletest.git --branch release-1.10.0
#        cd googletest
#        cmake -Bbuild -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION
#        cmake --build build --config Release
#        cmake --build build --target install --config Release
#        cd ../Particles

    - name: configure
      run: cmake -Bbuild -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/$INSTALL_LOCATION -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      
    - name: build
      run: cmake --build build --config $BUILD_TYPE -j4

    - name: run tests
      run: |
        cd build
        DYLD_LIBRARY_PATH=$(pwd) && ctest -C $BUILD_TYPE -VV

    - name: install project
      run: cmake --build build --target install --config Release 